apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-git
spec:
  template:
    spec:
      containers:
      - image: spring-petclinic-git 
        imagePullPolicy: Always
        name: spring-petclinic-git
        resources:
          requests:
            memory: 600Mi
            cpu: 100m
          limits:
            memory: 800Mi
            cpu: 200m
