apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  template:
    spec:
      containers:
      - image: spring-petclinic 
        imagePullPolicy: Always
        name: spring-petclinic
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
