apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  template:
    spec:
      containers:
      - image: spring-petclinic-minimal 
        imagePullPolicy: Always
        name: spring-petclinic-minimal
      resources:
        requests:
          memory: 100Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m