apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: spring-petclinic

resources:
- deployment.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: spring-petclinic
  env: ./environment 

crds:
- openshift-route.json
